export const response: Record<string, string> = {
    "100": "Internal server error.",
    "101": "Issue on fetch data. Try after some time.",
    "102": "No data found",
    "103": "Invalid request",
    "104": "Something went wrong. Try after some time.",
    "106": "Not Found",
    "109": "Invalid access token.",
    "110": "Request Not Found",
    "112": "File uploaded successfully.",
    "113": "File upload failed.",
    "114": "File deleted successfully.",
    "117": "Authorization token is required.",
    "118": "Invalid token payload structure.",
    "119": "Invalid public token.",
    "120": "Invalid public token payload structure.",

    "202": "Login successfully.",
    "203": "Password updated successfully.",
    "204": "Invalid Password.",
    "221": "User added successfully.",
    "222": "User updated successfully.",
    "223": "User activated successfully.",
    "224": "User details fetched successfully.",
    "225": "User not found.",
    "233": "",
    "236": "Password reset link sent to your email.",
    "237": "Reset token is invalid or has expired.",
    "267": "Shop list fetched successfully.",

    "481": "Purchase added successfully.",
    "482": "Purchase updated successfully.",
    "483": "Purchase deleted successfully.",
    "484": "Purchase details fetched successfully.",
    "485": "Purchase not found.",
    "487": "Purchase list fetched successfully.",

    "501": "Purchase detail added successfully.",
    "502": "Purchase detail updated successfully.",
    "503": "Purchase detail deleted successfully.",
    "504": "Purchase detail fetched successfully.",
    "505": "Purchase detail not found.",
    "507": "Purchase detail list fetched successfully.",
    "508": "Old purchase detail value fetched successfully.",
    "509": "Purchase detail item image updated successfully.",

    "601": "Purchase payment added successfully.",
    "602": "Purchase payment updated successfully.",
    "603": "Purchase payment deleted successfully.",
    "604": "Purchase payment details fetched successfully.",
    "605": "Purchase payment not found.",
    "607": "Purchase payment list fetched successfully."
};
